""" Monte-Carlo simulation module which is the core of the Cluster Expansion. The MC_Driver is interfaced to C-code.
The code is tested with Python 3.8.3 @IIT Bhubaneswar 2020 """
import sys
import os
import numpy as np
import string
import copy
import time
from random import randint, random
from more_itertools import unique_everseen
from Lacos.CPyMonC.miscfunctions import *
from Lacos.CPyMonC.Energy import ConfigurationEnergy, Convert_Clusters_to_IndexList, ConfigurationEnergy_Fast
from Lacos.CPyMonC.Utility import *
from Lacos.CPyMonC.POSCAR_handler import *
from Lacos.CPyMonC.Composition import *
from Lacos.CPyMonC.Cwrapper import C_MonteCarlo

MCLogFile = None

COORD_TOLERANCE = 1.e-5
NORM_TOLERANCE = 1.e-5
BOLTZMANN_CONSTANT = 8.6173303e-5


def MC_Driver(Base_Lattice, ClusterList, ECIList, ElementRep):
    """
    This method is the main driver for Monte Carlo.
    :param Base_Lattice:
    :param ClusterList:
    :param ECIList:
    :param ElementRep:
    :return: None
    """
    write_header('Monte-Carlo Inputs')
    MCLogFile_Name = "MC.log"
    MCOutputFile_Name = "MC.out"
    Restart_MC_from_file = read_yesno_input(
        "Restart Monte Carlo simulation from previous stopped run - input Y|N (Default is no): ", "Allow Blank")
    if Restart_MC_from_file == None or Restart_MC_from_file.strip() == "": Restart_MC_from_file = 'no'

    if 'y' in Restart_MC_from_file.lower():
        Restart_MC_FileName = read_string_input("  Give restart-file (should be one generated by previous run): ")
        Restart_MC_FileName = Restart_MC_FileName.strip()

    if 'y' in Restart_MC_from_file.lower():
        SuperLattice, Frozen_Elements = Read_MC_CheckPoint_File(Restart_MC_FileName, Base_Lattice, ElementRep)
    else:
        SuperLattice, Frozen_Elements = Prepare_MC_System(Base_Lattice, ElementRep)

    Temperature_Sequence, Equilibrium_Tolerance, Equilibrium_Steps, nSTEP_MOVAVG, MinEquil_Steps, Calculation_Steps, Block_Size = Get_MonteCarlo_Parameters()

    use_C_core = read_string_input(
        "\nUse C-core for Monte Carlo Simulation (Y|N) - For default (=\"Yes\") \"Enter\": ", "Allow Blank"
    )
    if use_C_core == None or use_C_core == '': use_C_core = 'yes'

    if 'y' in use_C_core.lower():
        Start_Time = time.time()
        C_MonteCarlo(MCLogFile_Name, MCOutputFile_Name, Base_Lattice, ElementRep, SuperLattice, Frozen_Elements,
                     Temperature_Sequence, Equilibrium_Steps, Equilibrium_Tolerance, nSTEP_MOVAVG, MinEquil_Steps,
                     Calculation_Steps, Block_Size, ClusterList, ECIList)
    else:
        Python_MonteCarlo(MCLogFile_Name, MCOutputFile_Name, Base_Lattice, ElementRep, SuperLattice, Frozen_Elements,
                          Temperature_Sequence, Equilibrium_Steps, Equilibrium_Tolerance, nSTEP_MOVAVG, MinEquil_Steps,
                          Calculation_Steps, Block_Size, ClusterList, ECIList)

    print('\nMonte Carlo simulation successfully completed: %f (sec)\n' % (time.time() - Start_Time))
    try:
        MCLogFile = open(MCLogFile_Name, 'a')
    except:
        exit_script("Unable to open Monte Carlo log file. Exit.")
    write_header('Monte Carlo simulation successfully completed', MCLogFile)
    MCLogFile.close()

    return


def Prepare_MC_System(Base_Lattice, ElementRep):
    """
    This method Prepare super cell to be used in MC simulation. Distribute atoms randomly on lattice after reading
    composition. :param Base_Lattice: :param ElementRep: :return: SuperLattice, Frozen_Elements.
    """
    Ncell = read_int_list_input("\nSize of the supercell: ", 3)
    if any(r == 0 for r in Ncell): exit_script("No dimension can be less than 1. Exit")
    SuperLattice = Create_Supercell_Fractional(Base_Lattice, Ncell, 'rel')
    SuperLattice['nCell'] = Ncell
    Composition = Read_Composition(Base_Lattice, list(ElementRep.keys()))
    SuperLattice = Fix_Composition_in_Supercell(SuperLattice, Base_Lattice, Composition)
    Frozen_Elements = List_Frozen_Elements(Composition)

    if set(SuperLattice['ElementList']) == set(Frozen_Elements):
        exit_script(
            "Error: All elements have been frozen. Cannot perform Monte-Carlo simulation. Exit"
        )

    if len(list(set(SuperLattice['ElementList']) - set(Frozen_Elements))) < 2:
        exit_script(
            "Error: Only one element is active (rest have been frozen)...Don't know how to perform Monte-Carlo "
            "simulation. Exit"
        )

    return SuperLattice, Frozen_Elements


def Get_MonteCarlo_Parameters():
    """
    This method will read all Monte Carlo parameters like T-sequence, energy tolerance, number of steps for
    equilibrium etc.
    :return: Temperature_Sequence, Equilibrium_Tolerance, Equilibrium_Steps, nSTEP_MOVAVG, MinEquil_Steps,
    Calculation_Steps, Block_Size

    """
    n = read_int_input("Number of cooling/heating rates (\"Enter\" for constant cooling/heating rate): ",
                       "Allow Blank")
    if n == None: n = 1
    if n == 1:
        Tinput = read_float_list_input(
            "\n   Give start and end (< start) temperatures (in Kelvin), and the step by which to change: ", 3
        )
        Temperature_Sequence = float_sequence(Tinput[0], Tinput[1], Tinput[2])
    else:
        Temperature_Sequence = []
        print(
            "\n   Give start and end (< start) temperatures (K), and the step by which to change for each of %d "
            "sequence (don't overlap temperature-ends between sequence): " % n
        )
        for _ in range(n):
            Tinput = read_float_list_input("   Sequence %d: " % (_ + 1), 3)
            Temperature_Sequence += [_ for _ in float_sequence(Tinput[0], Tinput[1], Tinput[2]) if
                                     _ not in Temperature_Sequence]

    nSTEP_MOVAVG = read_int_input("\nNumber of MC steps to calculate energy fluctuation (Default is 50): ",
                                  "Allow Blank")
    if nSTEP_MOVAVG == None: nSTEP_MOVAVG = 50

    MinEquil_Steps = read_int_input(
        "\nNumber of minimum MC blocks for equilibration - each Block is used for calculating energy fluctuation ("
        "Default is 2): ", "Allow Blank"
    )
    if MinEquil_Steps is None: MinEquil_Steps = 2

    _ = read_float_input(
        "\nGive fluctuation tolerance to achieve in equilibration - should be slope of standard deviation in energy "
        "(1e-5) | Alternatively give number of MC steps for equilibration: "
    )
    if _ < 1.0:
        Equilibrium_Tolerance = copy.copy(_)
        Equilibrium_Steps = None
    else:
        Equilibrium_Tolerance = None
        if int(_) < 2:
            Equilibrium_Steps = 2
        else:
            Equilibrium_Steps = int(_)

        nSTEP_MOVAVG = min(Equilibrium_Steps, nSTEP_MOVAVG)

    _ = read_int_list_input(
        "\nQuantities are calculated through block-averaging. Give number of blocks (> 0) and number of MC steps per "
        "block (> 5): ", 2)
    Block_Size = _[1]
    Calculation_Steps = _[0] * _[1]

    if _[0] < 1: exit_script("Number of blocks should be at-least 1. Exit")
    if _[1] < 5: exit_script("Number of MC-steps per block should be at least 5. Exit")

    return (Temperature_Sequence, Equilibrium_Tolerance, Equilibrium_Steps, nSTEP_MOVAVG,
            MinEquil_Steps, Calculation_Steps, Block_Size)


def Read_MC_CheckPoint_File(Restart_MC_FileName, Base_Lattice, ElementRep):
    """
    This method will read monte carlo check point file.
    :param Restart_MC_FileName:
    :param Base_Lattice:
    :param ElementRep:
    :return: SuperLattice, Frozen_Elements.
    """
    try:
        fp = open(Restart_MC_FileName, "r")
    except IOError as e:
        exit_script("Error: Unable to open Restart File %s. Exit" % Restart_MC_FileName)

    lines = [r.rstrip() for r in fp]
    SuperLattice = {}
    for j, ln in enumerate(lines):
        if 'Lattice_Vectors' in ln:
            SuperLattice['Lattice_Vectors'] = []
            for k in range(3):
                p = [float(_) for _ in re.split(r'[;,\s]\s*', lines[j + k + 1].strip())]
                if len(p) is not 3: exit_script(
                    "Error in reading Lattice Vectors in Restart file %s. Exit." % Restart_MC_FileName)
                SuperLattice['Lattice_Vectors'].append(p)
        elif 'nCell' in ln:
            SuperLattice['nCell'] = [int(_) for _ in re.split(r'[;,\s]\s*', ln.split('=')[1].strip())]
        elif 'Element_List' in ln:
            SuperLattice['ElementList'] = [_ for _ in re.split(r'[;,\s]\s*', ln.split('=')[1].strip())]
        elif 'Frozen_Elements' in ln:
            p = ln.split('=')[1].strip()
            if p == '':
                Frozen_Elements = []
            else:
                Frozen_Elements = [_ for _ in re.split(r'[;,\s]\s*', p)]
        elif 'Atom_Numbers' in ln:
            SuperLattice['AtomNumbers'] = [int(ln.split('=')[1].strip())]
        elif 'Coordinates' in ln:
            SuperLattice['Coordinates'] = []
            for k in range(SuperLattice['AtomNumbers'][0]):
                p = [_ for _ in re.split(r'[;,\s]\s*', lines[j + k + 1].strip())]
                SuperLattice['Coordinates'].append([float(p[0]), float(p[1]), float(p[2]), p[3], int(p[4])])

    print("\n ---> Read Configuration from file %s\n" % Restart_MC_FileName)
    return SuperLattice, Frozen_Elements


def Python_MonteCarlo(MCLogFile_Name, MCOutputFile_Name, Base_Lattice, ElementRep, SuperLattice, Frozen_Elements,
                      Temperature_Sequence, Equilibrium_Steps, Equilibrium_Tolerance, nSTEP_MOVAVG, MinEquil_Steps,
                      Calculation_Steps, Block_Size, ClusterList, ECIList):
    """
    This method is a Python-based Monte Carlo with Metropolis algorithm. Markon chain generated in configuration space
     by atom-exchange. The code is too slow for any real-use with respect to the C-code.
    :param MCLogFile_Name:
    :param MCOutputFile_Name:
    :param Base_Lattice:
    :param ElementRep:
    :param SuperLattice:
    :param Frozen_Elements:
    :param Temperature_Sequence:
    :param Equilibrium_Steps:
    :param Equilibrium_Tolerance:
    :param nSTEP_MOVAVG:
    :param MinEquil_Steps:
    :param Calculation_Steps:
    :param Block_Size:
    :param ClusterList:
    :param ECIList:
    :return: None.
    """
    SuperLattice['Coordinates'], SuperLattice['Keys'] = Create_Coordinate_Dictionary(SuperLattice['Coordinates'])

    ActiveElements = list(set(SuperLattice['ElementList']) - set(Frozen_Elements))
    SuperLattice['Active'] = [key for key in SuperLattice['Coordinates'] if
                              SuperLattice['Coordinates'][key][3] in ActiveElements]
    print("\nNumber of active sites are: %d" % len(SuperLattice['Active']))

    NeighbourList = Build_Neighbour_List(SuperLattice, Base_Lattice, Frozen_Elements)
    SiteBasedClusterList = Convert_Clusters_to_IndexList(SuperLattice, ClusterList)
    write_header('Starting Monte-Carlo loop (Python Code)')
    global MCLogFile
    try:
        MCLogFile = open(MCLogFile_Name, 'w')
    except:
        exit_script("Unable to open Monte Carlo log file. Exit.")

    try:
        MCOutputFile = open(MCOutputFile_Name, 'w')
    except:
        exit_script("Unable to open Monte Carlo output file. Exit.")
    write_header("Output from Monte-Carlo (Python code)", MCOutputFile)
    MCOutputFile.write(
        "\nTemperature (K), Average energy (eV/atom), Median energy (eV/atom) and STD (eV/atom)\n"
    )
    MCLogFile.write("Starting Monte Carlo Simulation\n")

    Outputs = []
    for TKelvin in Temperature_Sequence:
        MCLogFile.write("\nPerforming simulation for T = %f K\n" % TKelvin)
        print("\nPerforming simulation for T = %f K" % TKelvin)
        TkB = TKelvin * BOLTZMANN_CONSTANT
        if Equilibrium_Tolerance != None:
            SuperLattice, MCout = MonteCarlo_Steps(SuperLattice, TkB, Frozen_Elements, NeighbourList, ClusterList,
                                                   ECIList, ElementRep, SiteBasedClusterList, nSTEP_MOVAVG,
                                                   EneTol=Equilibrium_Tolerance)
        else:
            SuperLattice, MCout = MonteCarlo_Steps(SuperLattice, TkB, Frozen_Elements, NeighbourList, ClusterList,
                                                   ECIList, ElementRep, SiteBasedClusterList, nSTEP_MOVAVG,
                                                   MCSteps=Equilibrium_Steps)

        MCLogFile.write(
            "After Equilibration at %f K, total energy (eV/atom): %f\n" % (TKelvin, MCout['energy'])
        )
        MCLogFile.write(
            "Energy tolerance achieved in %d MC steps: %f\n" % (MCout['mcsteps'], MCout['enetol'])
        )
        TotEne = []
        nBlocks = int(Calculation_Steps / Block_Size)
        for _ in range(nBlocks):
            BlockEne = []
            for counter in range(Block_Size):
                SuperLattice, MCout = MonteCarlo_Steps(SuperLattice, TkB, Frozen_Elements, NeighbourList, ClusterList,
                                                       ECIList, ElementRep, SiteBasedClusterList, nSTEP_MOVAVG,
                                                       MCSteps=1)
                BlockEne.append(MCout['energy'])
            TotEne.append(np.mean(BlockEne))
        Outputs.append([TKelvin, np.mean(BlockEne), np.median(BlockEne), np.std(BlockEne)])
        MCLogFile.write(
            "Temperature, Average energy and (Block-Averaged) STD (eV/atom): %s\n" % ", ".join(
                str(_) for _ in Outputs[-1])
        )
        MCOutputFile.write("  ".join('{:15.10f}'.format(_) for _ in Outputs[-1]) + "\n")
        MCLogFile.flush()
        MCOutputFile.flush()
        Write_POSCAR(Config_2_POSCAR(SuperLattice, Base_Lattice), "Configuration T = " + str(TKelvin),
                     "Config_" + str(TKelvin) + ".poscar")
        Write_CheckPoint_File(SuperLattice, Frozen_Elements, TKelvin)

    MCLogFile.close()
    MCOutputFile.close()

    return


def MonteCarlo_Steps(inLattice, TkB, Frozen_Elements, nnbList, ClusterList, ECIList, ElementRep, SiteBasedClusterList,
                     nSTEP_MOVAVG, EneTol=None, MCSteps=None):
    """
    This method is the main monte carlo working steps.
    :param inLattice:
    :param TkB:
    :param Frozen_Elements:
    :param nnbList:
    :param ClusterList:
    :param ECIList:
    :param ElementRep:
    :param SiteBasedClusterList:
    :param nSTEP_MOVAVG:
    :param EneTol:
    :param MCSteps:
    :return: A dictionary type.
    """
    N = len(inLattice['Coordinates'])
    nActive = len(inLattice['Active'])
    MCSteps_Reached, nB, MeanStdE = 0, 0, 0.0
    Ehist = [ConfigurationEnergy_Fast(inLattice, ClusterList, ECIList, ElementRep, SiteBasedClusterList)]
    EperMC = [Ehist[-1]]

    while True:

        for _ in range(nActive):
            site_key = inLattice['Active'][randint(0, nActive - 1)]
            if inLattice['Coordinates'][site_key][3] in Frozen_Elements: continue
            jsite_key = nnbList[site_key][randint(0, len(nnbList[site_key]) - 1)]
            inLattice['Coordinates'][site_key][3], inLattice['Coordinates'][jsite_key][3] = \
                inLattice['Coordinates'][jsite_key][3], inLattice['Coordinates'][site_key][3]
            Enew = ConfigurationEnergy_Fast(inLattice, ClusterList, ECIList, ElementRep, SiteBasedClusterList)
            dE = (Enew - Ehist[-1]) * N
            if dE < 0.0:
                Ehist.append(Enew)
            else:
                X = random()
                if X < exp(-dE / TkB):
                    Ehist.append(Enew)
                else:
                    inLattice['Coordinates'][site_key][3], inLattice['Coordinates'][jsite_key][3] = \
                        inLattice['Coordinates'][jsite_key][3], inLattice['Coordinates'][site_key][3]

        MCSteps_Reached += 1
        EperMC.append(Ehist[-1])
        MCLogFile.write("%d %f\n" % (MCSteps_Reached, EperMC[-1]))
        if MCSteps_Reached >= nSTEP_MOVAVG:
            StdE = np.std(np.array(EperMC[-nSTEP_MOVAVG:]))
            tmp_MeanStdE = (MeanStdE * nB) / (nB + 1.0) + StdE / (nB + 1.0)
            if EneTol != None and abs(MeanStdE - tmp_MeanStdE) < EneTol:
                return inLattice, {'energy': Ehist[-1], 'enetol': abs(MeanStdE - tmp_MeanStdE),
                                   'mcsteps': MCSteps_Reached}
            MeanStdE = tmp_MeanStdE
        if MCSteps != None and MCSteps_Reached == MCSteps:
            return inLattice, {'energy': Ehist[-1], 'enetol': -1.0, 'mcsteps': MCSteps_Reached}


def Periodic_Distance(R0, R1, ncell):
    """
    This method is for the distance that obeys periodic boundary condition
    :param R0:
    :param R1:
    :param ncell:
    :return:
    """
    dR = np.abs(np.array(R0[:3]) - np.array(R1[:3]))
    dR = [dR[i] - ncell[i] if dR[i] > ncell[i] / 2.0 else dR[i] for i in range(3)]
    return np.linalg.norm(dR)


def Minimal_Distance(base_lattice):
    """
    This method finds the minimal distance (nearest-neighbor distance).
    :param base_lattice:
    :return: A dictionary type.
    """
    minDist = {}
    for (j, R0) in enumerate(base_lattice['Coordinates']):
        _ = [Periodic_Distance(R0, R1, [1.0, 1.0, 1.0]) for R1 in base_lattice['Coordinates']]
        _ = [r for r in _ if r > NORM_TOLERANCE]
        if len(_) > 0:
            minDist[j] = min(_)
        else:
            minDist[j] = 1.0
    return minDist


def Build_Neighbour_List(inLattice, base_lattice, Frozen_Elements):
    """
    This method is for all active sites, store all 'neighbour'-sites in an array.
    :param inLattice:
    :param base_lattice:
    :param Frozen_Elements:
    :return: nnblist: A dictionary type.
    """
    ext_minDist = read_float_input(
        "\nGive distance within which to exchange atoms, calculated using fractional coordinates (for default "
        "Nearest-neighbor, just \"Enter\"):", "Allow Blank"
    )
    if ext_minDist is None:
        minDist = Minimal_Distance(base_lattice)
    else:
        minDist = [ext_minDist] * len(inLattice['Coordinates'])
    count_attempt = 0
    while True:
        count_attempt += 1
        nnblist = {}
        nnbEmpty = []
        for (j, R0) in inLattice['Coordinates'].items():
            if inLattice['Coordinates'][j][3] in Frozen_Elements:
                nnblist[j] = []
            else:
                nnblist[j] = [k for (k, R1) in inLattice['Coordinates'].items() if j != k and \
                              Periodic_Distance(R0, R1, inLattice['nCell']) < (minDist[R0[4]] + NORM_TOLERANCE) and \
                              inLattice['Coordinates'][k][3] not in Frozen_Elements]
                nnblist[j] = list(set(nnblist[j]))
                nnbEmpty.append(True if nnblist[j] == [] else False)

        if any(nnbEmpty):
            print_warning(
                'Sites found with empty neighbour-list and occupied by atom not in frozen-element list.'
            )
            ext_minDist = read_float_input(
                "\nIncrease the distance to search for atom-exchange (calculated using fractional coordinates):"
            )
            minDist = [ext_minDist] * len(inLattice['Coordinates'])
        else:
            return nnblist

        if count_attempt == 3:
            exit_script(
                "After three attempts, unable to build nearest-neighbour list for atom-exchange. Exit Monte Carlo."
            )
